name: UT Coverage for New PR
description: UT Coverage for New PR
author: guguducken

inputs:
  github-token:
    description: 'The user GitHub token for get data'
    required: true
    default: ${{ github.token }}

outputs:
  paths:
    description: 'The paths of this PR changed'

runs:
  using: 'node16'
  main: 'src/index.js'
